#!/usr/bin/env bash

# set -e : Exit the script if any statement returns a non-true return value.
# set -u : Exit the script when using uninitialised variable.
set -eu

printenv

# Add libraries
source /usr/local/lib/bash-logger.sh
source /usr/local/lib/persist-env.sh

# Redirect STDERR to STDOUT
exec 2>&1

# make sure folders exist
mkdir -p /etc/caddy/certificates

# Default values
CADDY_STARTPARAMS=${CADDY_STARTPARAMS:='-conf=/etc/caddy/Caddyfile --log=stdout'}
CADDY_STARTPARAMS="${CADDY_STARTPARAMS} -agree=${CADDY_AGREE:=false}"
CADDY_STARTPARAMS="${CADDY_STARTPARAMS} -ca=${CADDY_CA:=https://acme-v01.api.letsencrypt.org/directory}"
CADDY_STARTPARAMS="${CADDY_STARTPARAMS} -catimeout=${CADDY_CA_TIMEOUT:=10s}"
CADDY_STARTPARAMS="${CADDY_STARTPARAMS} -cpu=${CADDY_CPU:=100%}"
CADDY_STARTPARAMS="${CADDY_STARTPARAMS} -email=${CADDY_EMAIL:=}"
CADDY_STARTPARAMS="${CADDY_STARTPARAMS} -grace=${CADDY_GRACE:=5s}"
CADDY_STARTPARAMS="${CADDY_STARTPARAMS} -http2=${CADDY_HTTP2:=true}"
CADDY_STARTPARAMS="${CADDY_STARTPARAMS} -quiet=${CADDY_QUIET:=false}"
CADDY_STARTPARAMS="${CADDY_STARTPARAMS} -port=${CADDY_PORT:=2015}"
CADDY_STARTPARAMS="${CADDY_STARTPARAMS} -http-port=${CADDY_HTTP_PORT:=80}"
CADDY_STARTPARAMS="${CADDY_STARTPARAMS} -https-port=${CADDY_HTTPS_PORT:=443}"

# Changed defaut certificates folder
CADDYPATH=${CADDYPATH:=/etc/caddy/certificates}


# A Caddyfile must exist in /etc/caddy
# if not, just create a default simple one
if [ ! -f /etc/caddy/Caddyfile ]; then
    echo "# Caddy config file" > /etc/caddy/Caddyfile
    echo "# See: https://caddyserver.com/docs/caddyfile" >> /etc/caddy/Caddyfile
    echo "" >> /etc/caddy/Caddyfile
    echo "0.0.0.0" >> /etc/caddy/Caddyfile
    echo "root /var/www" >> /etc/caddy/Caddyfile
    echo "log stdout" >> /etc/caddy/Caddyfile
    echo "errors stdout" >> /etc/caddy/Caddyfile
    chown caddy:caddy /etc/caddy/Caddyfile
fi

# Let's go and start Caddy
NOTICE "[CADDY] -- Starting Service caddy ..."
exec su-exec caddy /usr/bin/caddy ${CADDY_STARTPARAMS}

# This exit code will be sent as the first parameter to the finish script
exit 1
