
FROM dsuite/alpine-runit:3.9

LABEL maintainer="Hexosse <hexosse@gmail.com>" \
      description="Minimal Alpine image with Caddy server." \
      vendor="docker-suite" \
      license="MIT"


## Current Caddy version
ENV CADDY_VERSION=0.10


## Caddy packages
COPY --from=dsuite/repo-caddy:0.10 /repo /tmp/repo
COPY --from=dsuite/repo-caddy:0.10 /etc/apk/keys/caddy* /etc/apk/keys


## Install
RUN \
	# Print executed commands
	set -x \
    # Update repository indexes
    && apk-update \
    # Install Caddy server
    && apk-install --repository /tmp/repo/v3.9 \
        caddy-0.10 \
	# Clear apk's cache
	&& apk-cleanup


## Copy scripts
COPY /rootfs /


## Add volume to allow persistence
VOLUME ["/etc/caddy", "/etc/caddy/certificates", "/var/www", "/var/log"]


## Expose http, https and caddy port
EXPOSE 80 443 2015
