#!/usr/bin/env bash

# Add libraries
source /usr/local/lib/bash-logger.sh
source /usr/local/lib/persist-env.sh

WARNING "[CADDY] -- Ending Service caddy with parameters ${@}"

# Tell runit to shutdown the system:
[ "$1" = 1 ] && runit stop &
